# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emerge_api', '0002_auto_20161023_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
