# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 07:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emerge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='contact',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='\\D*([2-9]\\d{2})(\\D*)([2-9]\\d{2})(\\D*)(\\d{4})\\D*')]),
        ),
    ]
